In [2]:
import tensorflow as tf

In [12]:
number = 5
numbertf = tf.constant(8, dtype=tf.float32)
arr = [2,3,4]
arrtf = tf.constant([2,3,4], dtype=tf.float32)
marrtf = tf.constant([[2,3,4], [2,3,1]], dtype=tf.float32)

In [14]:
marrtf

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[2., 3., 4.],
       [2., 3., 1.]], dtype=float32)>

In [15]:
gen_all_ones = tf.ones(shape=(3,3))

In [16]:
gen_all_ones

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [17]:
get_all_zeros = tf.zeros(shape=(2,6))

In [19]:
get_all_zeros.numpy()

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]], dtype=float32)

In [25]:
make_normal = tf.random.normal(shape=(5,5), mean=0, stddev=1,dtype=tf.float32)

In [27]:
make_normal

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[ 2.2506173 , -0.67152566,  1.6389341 ,  0.14178842,  0.8495516 ],
       [-0.01045796,  0.07184668, -0.47995135,  0.6722547 ,  0.51872486],
       [-1.539747  ,  0.35265267, -0.40891528, -0.80511206,  0.82935584],
       [-0.00433915,  2.3392878 , -1.0154169 ,  0.2789417 ,  0.22081855],
       [ 0.24945144, -0.5620557 ,  0.6429601 , -0.4729768 , -0.3758014 ]],
      dtype=float32)>

In [29]:
make_normal_casted = tf.cast(make_normal, dtype=tf.float16)

In [30]:
make_normal_casted.numpy()

array([[ 2.25    , -0.6714  ,  1.639   ,  0.1418  ,  0.8496  ],
       [-0.01046 ,  0.07184 , -0.48    ,  0.6724  ,  0.5186  ],
       [-1.54    ,  0.3525  , -0.409   , -0.805   ,  0.8296  ],
       [-0.004337,  2.34    , -1.016   ,  0.279   ,  0.2208  ],
       [ 0.2495  , -0.562   ,  0.643   , -0.473   , -0.3757  ]],
      dtype=float16)

In [31]:
tf.random.uniform(shape=(3,3) , minval=1, maxval=5)

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[1.5687094, 1.8350711, 2.2786913],
       [4.637935 , 3.8409667, 4.797203 ],
       [2.2958431, 2.6101003, 1.9757419]], dtype=float32)>

In [38]:
make = tf.range(start=1, limit=10)

In [40]:
make

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [42]:
make2 = tf.reshape(make, shape=(3,3))
make2

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]], dtype=int32)>

In [43]:
tf.cast(make2, dtype=tf.float32)

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]], dtype=float32)>

In [ ]:
# tf.eye(
#     num_rows, num_columns=None, batch_shape=None, dtype=tf.dtypes.float32, name=None
# )

In [44]:
tf.eye(num_rows=3, num_columns=5, name="gen", dtype=tf.float32)

<tf.Tensor: shape=(3, 5), dtype=float32, numpy=
array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.]], dtype=float32)>

In [45]:
# tf.fill([2, 3], 9)

tf.fill([3,3], 0)


<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]], dtype=int32)>

In [50]:
a = tf.constant([
     [1,2,3],
     [2,3,2],
     [1,1,1]


],dtype=tf.float32)


b = tf.constant([
     [1,2,3],
     [2,3,2],
     [1,1,1]


],dtype=tf.float32)

In [51]:
a+b

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[2., 4., 6.],
       [4., 6., 4.],
       [2., 2., 2.]], dtype=float32)>

In [52]:
tf.add(a,b)

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[2., 4., 6.],
       [4., 6., 4.],
       [2., 2., 2.]], dtype=float32)>

In [57]:
tf.reduce_sum(a *b)

<tf.Tensor: shape=(), dtype=float32, numpy=34.0>

In [58]:
a -b 

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

In [59]:
tf.subtract(a,b)

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

In [61]:
tf.multiply(a,b)

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[1., 4., 9.],
       [4., 9., 4.],
       [1., 1., 1.]], dtype=float32)>

In [62]:
a *b

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[1., 4., 9.],
       [4., 9., 4.],
       [1., 1., 1.]], dtype=float32)>

In [63]:
a @ b

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[ 8., 11., 10.],
       [10., 15., 14.],
       [ 4.,  6.,  6.]], dtype=float32)>

In [68]:
m = tf.matmul(a,b)

In [80]:
type(m.numpy())

numpy.ndarray